pogo_transport: fix printf format
pogo/pogo_transport.c:2690:1: error: format specifies type 'unsigned long' but the argument has type 'u64' (aka 'unsigned long long') [-Werror,-Wformat]
POGO_TRANSPORT_DEBUGFS_RW(acc_charging_timeout_sec);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pogo/pogo_transport.c:2676:9: note: expanded from macro 'POGO_TRANSPORT_DEBUGFS_RW'
                      pogo_transport->_name);                                                   \
                      ^~~~~~~~~~~~~~~~~~~~~

Note that some members of struct pogo_transport that are being logged
via POGO_TRANSPORT_DEBUGFS_RW() are u64 and some are unsigned long. To
avoid all printf format issues, they all are now unconditionally cast
to u64.

Fixes: 445cabfbdd60 ("pogo_transport: Implement lc events")
Test: TH
Bug: 348164658
Change-Id: Ic49dd94bca72a0c856828ae3ce351fadeb6717d8
Signed-off-by: André Draszik <draszik@google.com>