touch: fix build error due to -isystem removal
Upstream commit 04e85bbf71c9 ("isystem: delete global -isystem compile
option") requires using in-tree minimal stddef header. Fixes:

  touch/fts/ftm5/fts_lib/ftsTime.c:30:10:
  fatal error: 'stdarg.h' file not found
  #include <stdarg.h>

Bug: 283901427

Change-Id: I77e9e0043ec94e58a0f94cbcc7d0e822a3bc2d8f
Signed-off-by: Samuel Gosselin <sgosselin@google.com>